# PlasAnnotatoR v2.0 - Configuración central
project:
  name: PlasAnnotatoR
  version: "2.0"
  output_dir: results/

environments:
  plasclass:
    conda_base: /home/bionfo/micromamba/envs/plasclass
    python: /home/bionfo/micromamba/envs/plasclass/bin/python
    script: /home/bionfo/micromamba/envs/plasclass/bin/classify_fasta.py
    threshold: 0.5

  plasme:
    conda_base: /home/bionfo/anaconda3/envs/plasme
    script: /home/bionfo/PLASMe/PLASMe.py
    database: /home/bionfo/PLASMe/DB
    threshold: 0.5

  plasmidhunter:
    conda_base: /home/bionfo/micromamba/envs/plasmidhunter
    script: /home/bionfo/micromamba/envs/plasmidhunter/bin/plasmidhunter
    threshold: 0.5

  rf_model:
    model_path: data/models/rf_model.pkl

ensemble:
  weights:
    plasclass: 0.9017
    plasme: 0.9748
    plasmidhunter: 0.9178
    rf_model: 0.9872
  min_votes: 3
  final_threshold: 0.5

databases:
  plsdb: data/plsdb/sequences.fasta
  metadata: data/plsdb/meta/nuccore.csv
  amr: data/plsdb/meta/amr.tsv
  typing: data/plsdb/meta/typing.csv
  taxonomy: data/plsdb/meta/taxonomy.csv
  card: data/indexes/nucleotide_fasta_protein_homolog_model.fasta
  mibig: data/indexes/mibig_4.0.fasta
  cazy:  data/indexes/cazy.fasta

resources:
  threads: 8
  memory_gb: 16
  temp_dir: temp/